### ISSUE TITLE
msvc编译问题

### ISSUE THREAD

**Issue by IULOVE** [YuriSizuku/MemoryModule#1]
直接在工程引用这个msvc报错
![Quicker_20220404_124310](https://user-images.githubusercontent.com/14193276/161475301-924b8089-652b-4650-9a0e-6399fd2f6e1b.png)
void* + 偏移这些

**Comment by YuriSizuku** [comment]
This is because the msvc can not use (void *) variable add offset. Now I fixed this problem by using (uint8_t *)
