### ISSUE TITLE
winpe_memGetProcAddress，Can you provide a hash version of this function?

### ISSUE THREAD

**Issue by icyfox168168** [YuriSizuku/MemoryModule#7]
Can you provide a hash version of this function?

**Comment by YuriSizuku** [comment]
You can use this function winpe_memfindexpcrc32. 
This is almost similary with winpe_memGetProcAddress,
without the forward to other dll function. 

```
WINPEDEF WINPE_EXPORT
INLINE void* STDCALL winpe_memfindexpcrc32(
    void* mempe, uint32_t crc32);
```

**Comment by icyfox168168** [comment]
winpe_findmoduleaex 

No hash version was found for this function
