### ISSUE TITLE
printf("%p\n", GetProcAddress(LoadLibraryA("kernel32.dll"), "readfile"));

### ISSUE THREAD

**Issue by icyfox168168** [YuriSizuku/MemoryModule#8]
Serious problem, normally get 0, but can get the address

**Comment by icyfox168168** [comment]
Can't you reproduce this problem? It is inconsistent with the return value of the function GetProcAddress. It should be a bug in the function character judgment.

**Comment by YuriSizuku** [comment]
I can not reproduce this. I think it is not a problem. 
Beacuse windows apis are case sensitive. Although module file is not. 
You should be careful about that, use as this

```
printf("%p\n", winpe_memGetProcAddress(LoadLibraryA("kernel32.dll"), "ReadFile"));
```
