### ISSUE TITLE
加载时崩溃了

### ISSUE THREAD

**Issue by afengsoft** [YuriSizuku/MemoryModule#9]
崩溃在winpe.h文件的784行，funcname有问题
 funcva = (size_t)pfnGetProcAddress((HMODULE)dllbase, funcname);

有一些DLL是没函数名，只提供了Ordinal

**Comment by YuriSizuku** [comment]
哪些函数， 如何进行复现？

**Comment by YuriSizuku** [comment]
I will close this issue if no more infomation.
